<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>手写PROMISE</title>
    <script src="./utils/utils.js"></script>
  </head>
  <body>
    <script>
      //定义三个状态
      const PENDING = 'pending',
        FULFILLED = 'fulfilled',
        REJECTED = 'rejected'
      class myPromise {
        constructor(executor) {
          //设置初始状态
          this.status = PENDING
          this.value = undefined
          this.reason = undefined
          //定义事件池
          this.onFulfilledCallbacks = []
          this.onRejectedCallbacks = []
          //new PROMISE实例的时候会执行executor函数
          const resolve = (value) => {
            if (this.status === PENDING) {
              this.status = FULFILLED
              this.value = value
              if (this.onFulfilledCallbacks.length > 0) {
                // 注意：要在这里把要执行的函数放到微任务队列，在then里面包裹只是把push这个操作放到了微任务队列
                queueMicrotask(() => {
                  this.onFulfilledCallbacks.forEach((fn) => fn())
                })
              }
            }
          }
          const reject = (reason) => {
            if (this.status === PENDING) {
              this.status = REJECTED
              this.reason = reason
              if (this.onRejectedCallbacks.length > 0) {
                // 注意：要在这里把要执行的函数放到微任务队列，在then里面包裹只是把push这个操作放到了微任务队列
                queueMicrotask(() => {
                  this.onRejectedCallbacks.forEach((fn) => fn())
                })
              }
            }
          }
          //注意：原生promise源码并没有对异步的语法错误进行捕获
          try {
            executor(resolve, reject)
          } catch (err) {
            reject(err.message)
          }
        }
        //then接收2个参数onFulfilled, onRejected,支持链式调用,则then返回的也是一个PROMISE

        then(onFulfilled, onRejected) {
          //注意：这里的任务需要放在微任务队列执行-此处代码没做处理了
          let p2 = new myPromise((resolve, reject) => {
            if (this.status === FULFILLED) {
              //then里面的方法放在微任务队列中执行
              queueMicrotask(() => {
                try {
                  const x = onFulfilled(this.value)
                  //2.如果返回的结果是promise，return的结果就是这个promise的结果
                  if (x instanceof myPromise) {
                    console.log(`x是一个promise对象`)
                    x.then(resolve, reject)
                  } else {
                    //3.如果x不是promise,返回的promise就会成功,并把x当做VALUE传给resolve
                    resolve(x)
                  }
                } catch (err) {
                  //1.代码报错，则捕获错误信息，直接reject
                  reject(err)
                }
              })
              //在这里需要判断X是普通值还是PROMISE,如果是普通值,直接resolve
            }
            if (this.status === REJECTED) {
              //then里面的方法放在微任务队列中执行
              queueMicrotask(() => {
                onRejected(this.reason)
              })
            }

            //异步的时候，PROMISE的状态是PENDING,并不会等待,而是添加事件池，让PROMISE成功或者失败的时候执行
            if (this.status === PENDING) {
              this.onFulfilledCallbacks.push(() => {
                onFulfilled(this.value)
              })
              this.onRejectedCallbacks.push(() => {
                onRejected(this.reason)
              })
            }
          })
          return p2
        }
      }

      var p = new myPromise((resolve, reject) => {
        resolve('Resolve SUCCESS')
        // reject('REJECT FAIL')
        // console.log('记录同步---修改状态。。。')
        // resolve(a)
        setTimeout(() => {
          // resolve(a) 这种错误无法捕获
          // resolve('Resolve Success after 1s')
          // reject('Reject Fail after 1s')
          // console.log('记录异步---修改状态。。。')
        }, 1000)
      })
      p.then(
        (res) => {
          console.log('resolve1111: ', res)
          // return new myPromise((r, j) => r(8888))
          return 8888
        },
        (err) => {
          console.log('reject1111: ', err)
          return 9999
        }
      ).then(
        (res) => {
          console.log('resolve2222: ', res)
          return '哈哈哈哈哈哈'
        },
        (err) => {
          console.log('reject2222: ', err)
        }
      )
      .then(
        (res) => {
          console.log('resolve3333: ', res)

        },
        (err) => {
          console.log('reject3333: ', err)
        }
      )
      console.log('我是主栈的任务，代码在最后。。。')
    </script>
  </body>
</html>
